---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install Docker
    yum: name=docker state=present
  - name: Start Docker
    service: name=docker state=started
  - name: Get the dockerfile  
